### ISSUE TITLE
return current pageX, pageY with the event

### ISSUE THREAD

**Issue by usmonster** [briancherne/jquery-hoverIntent#11]
It could be generally useful if the event passed to the handlers could also hold the current X & Y coordinates of the mouse at the time of firing. This could be added as part of the event.data, or more seamlessly (though potentially an unwanted side-effect for some) copied over the pageX/pageY of the returned event itself. This would make it much easier for those who want their handler to, for example, position something relative to the location of the pointer at the time of firing.

Thoughts? If I have time and there's interest, I can put an example implementation in a pull request.

**Comment by briancherne** [comment]
@usmonster - I'm in agreement with the copy-coordinates approach, as the default (and only) behavior. Just make sure to increment the version and note the (possible) backwards incompatibility for folks that were using the pageX/pageY of the original event. If someone complains we can consider adding a configuration option.

**Comment by usmonster** [comment]
While implementing this I realize the possibility that the most common use case may care about the current pointer coordinates only for the `over` handler and not for `out`. That said, I'm hesitating--should I still copy the current values onto both events (for consistency), or is it better to copy them only for the `over` handler?

Copying current coordinates to the event passed to `out` would still allow access to the `originalEvent`'s coordinates, though this could arguably be a more surprising/less intuitive default behavior..

Anyone have a compelling use case to support either option?

**Comment by usmonster** [comment]
Actually, I've just convinced myself that it's fine to copy both, I'll just document this change.

**Comment by usmonster** [comment]
I keep going back and forth on consistency vs. intuition issue, and it's blocking the release...

Basically, I'd just like some/any feedback as to whether it makes more sense to leave the `out` handler event as-is (it has the pointer coordinates of the original *mouseleave* event), or if it's objectively better to give it the coordinates that are "current" at the moment when the handler is called (i.e. after the `timeout`, if any is given--this would require additional mousemove tracking between the mouseleave and said timeout).

Thoughts? @flesler, @roydukkey, @briancherne?

**Comment by roydukkey** [comment]
In my opinion it makes sense to leave it the way it currently is, because *out* means, well when the mouse moves *out*. So my vote is to leave `e.pageX` and `e.pageY` alone.

It would be easy to add `e.delayedPageX` and `e.delayedPageY`. But, I'm not in favour of modifying the behaviour of jQuery.

Wouldn't it be fine to update the `out` signature to include a parameter for things that are additional to jQuery? Something along these lines:

```
// out: Function( Event eventObject, Object delayedCoord )

$( "p" ).hoverIntent( function() { }, function( event, delayed ) {
     delayed.pageX;
     delayed.pageY;
});
```

**Comment by usmonster** [comment]
Thanks for the rapid feedback, @roydukkey! I agree with the semantics of *out*, though the same reasoning could be applied to the *over* case. One can imagine valid use cases where someone might want to have access to the actual handler-time coordinates instead of (or in addition to) the event-time coordinates for both mouseenter/"over" *and* mouseleave/"out" cases. Applying the same kind of modification for both event/handler pairs would also preserve a kind of semantic and behavioral symmetry.

All that said, I may be leaning slightly toward leaving the mouseleave/out case alone, at least for this release, since the necessity of the change is currently less compelling than for the mouseenter/over case. Still, I'll leave the issue open a bit for other feedback until a decision is made.

As for the proposed alternatives, I doubt we'd add a `delayedPageX` value to the event or change the API of the handler in any case, especially since the latter could arguably be a more disruptive change. thanks for the suggestions, though!

**Comment by roydukkey** [comment]
Right. I did overlook the *over* case, but do you mind elaborating on how you feel the latter could be disruptive? Though the handler would be applied as `Function( Event eventObject, Object delayedCoord )` both parameters are still optional and do not present any new requirements in implementing hoverIntent. `out: function() { }` and `out: function( event ) { }` would still be acceptable without any issue.

**Comment by usmonster** [comment]
No problem! To elaborate, the disruption I was talking about is more to the users of the plugin, since hoverIntent is meant to be a drop-in replacement for `.hover`. If hoverIntent passed its own proprietary object to the handler--which can be any user-provided function--we have no guarantee that the function would behave the same. What if someone reuses the `out` function elsewhere and it already has different behavior based on its arguments? This would break for them. I think most behavior changes like this should be done in a way that doesn't change the API/contract that says "we will only pass an Event to the callback, even if your callback can take more arguments." Hope that makes sense.
