### ISSUE TITLE
hoverIntent does not work well with Bower.

### ISSUE THREAD

**Issue by tisto** [briancherne/jquery-hoverIntent#26]
As far as I can see it is impossible to install a specific version of hoverIntent with Bower. If I do:

$ bower install jquery.hoverIntent

it will install the latest version. Though, if I want to pin a version:

$ bower install jquery.hoverIntent#r7

or even:

$ bower install jquery.hoverIntent#v1.8.0

Bower will fail:

bower not-cached    git://github.com/LeMisterV/jquery.hoverintent.git#r7
bower resolve       git://github.com/LeMisterV/jquery.hoverintent.git#r7
bower ENORESTARGET  Tag/branch r7 does not exist

Is it possible to fix this in order to be able to install older versions of hoverIntent (or just pin the current version)?

**Comment by rjksn** [comment]
Hey, to steal the thunder here. How do you then use it, after `bower install jquery-hoverIntent`?
