### ISSUE TITLE
Minified version

### ISSUE THREAD

**Issue by matt-bailey** [briancherne/jquery-hoverIntent#32]
Any chance of including a minified version of the file?

That way I can skip a step in my grunt workflow, i.e. just copy the file straight to wherever I need it, rather than having to uglify it first.

**Comment by briancherne** [comment]
I can see the benefit of having a standard/approved minified version (I offer one on my web site, not tied to the github repo), but as @usmonster mentions it would require a change in development process... thus work.

I'd like to see 3 people "+1" this issue/feature request before we add it, or close it after a year of inactivity.

**Comment by kimoi** [comment]
+1

**Comment by alebruck** [comment]
+1

**Comment by coliff** [comment]
+1

**Comment by minorgod** [comment]
+1

**Comment by usmonster** [comment]
FYI, a minified file will be included in the [upcoming version](/briancherne/jquery-hoverIntent/milestones/v1.9.0), so the poll requires no more votes. :) Thanks to all who made the desire for this feature known!

**Comment by den67rus** [comment]
+1

**Comment by usmonster** [comment]
After several years, this issue has finally been addressed in the PR #64. Any interested person can feel free to review the PR and leave comments (there are already some open questions there), or it will be merged within the next two weeks. Thanks!
