### ISSUE TITLE
Most recent hoverIntent initialisation break previous ones.

### ISSUE THREAD

**Issue by roydukkey** [briancherne/jquery-hoverIntent#35]
HoverIntent blows away all previous initialisation. 

http://jsfiddle.net/7px1e2kd/1/

**Comment by usmonster** [comment]
Ooh, yeah, that's a bug. My first guess is that it's because the timeout ID is being shared across handlers, since it's always attached to the element and not the jQuery instance. I'll take a look. Thanks!

**Comment by usmonster** [comment]
Actually, this is probably the same issue as #28..

**Comment by usmonster** [comment]
After finally having some time to look further into this, I can confirm that the bug is indeed a result of how certain state information is stored per-element when it really should be per-instance-per-element. (Also it's completely unrelated to #28.) Fix forthcoming!

**Comment by usmonster** [comment]
@roydukkey would you care to take a look at #39 and see if it fixes your problem (and doesn't cause new ones)? Feel free to leave comments on the pull request.
