### ISSUE TITLE
add to npm

### ISSUE THREAD

**Issue by usmonster** [briancherne/jquery-hoverIntent#40]
I guess this should be officially added to npm? There are a couple folks who registered unofficial clones, but it might be best to have the official one in the registry, yes?

+1 (or make a pull request!) if you want this to happen. (Maybe pair this with #32?)

**Comment by jpdesigndev** [comment]
+1

**Comment by rohmann** [comment]
+1

**Comment by k-lange** [comment]
+1

**Comment by dandonahoe** [comment]
+1

**Comment by dnasir** [comment]
+1

**Comment by hdavidzhu** [comment]
+1
Is there a better way to do +1's in Github? I always feel that they contribute little to the conversation and don't dictate how many people (percentage-wise and stuff like that) would really want a new feature.

**Comment by dandonahoe** [comment]
Until github creates a "like" style button or something like stackoverflow, that's the best there is. I have nothing better to contribute except to express that the original poster was not alone in their request. 

Seems weird that feature doesn't exist.

**Comment by usmonster** [comment]
On Bugzilla and JIRA you have votes, and even on Google Code you could star issues. The closest equivalent on Github is subscribing to an issue, though it's kind of passive compared to the +1. In any case, after so much feedback, this will be added to NPM in the next release. :)

**Comment by kuzvac** [comment]
+1 :)

**Comment by usmonster** [comment]
Hey, folks! After an unreasonable amount of time, this issue is finally (mostly) addressed in the open PR #64.

To any interested person: please feel free to *review the PR and leave comments* (there are already some open questions there), or it will be merged mostly as-is within the next two weeks. Thanks, and sorry for the delay!
