### ISSUE TITLE
Compatibility for jQuery 2.x

### ISSUE THREAD

**Issue by SpikeShape** [briancherne/jquery-hoverIntent#45]
I am facing a compatibility problem when the event is handled:

```
TypeError: $.event.handle is undefined
````
on line 120
Apparently jQuery 2.x doesnt have the event.handle property.

I would really appreciate a compatibility fix or something instead of downgrading my jQuery version

**Comment by usmonster** [comment]
I'm not sure this is a compatibility issue.. can you make a JSFiddle that shows the problem you're having?

**Comment by SpikeShape** [comment]
Well - as it turns out I picked the wrong plugin which was released back in 2011. The bower package was named jquery.hoverIntent but yours is jquery-hoverIntent so nevermind. Yours is working like a charm.
