### ISSUE TITLE
create gh-pages branch, change official site to github.io

### ISSUE THREAD

**Issue by TheDigitalOrchard** [briancherne/jquery-hoverIntent#47]
Your website still has 1.8.0 even though 1.8.1 has been released

**Comment by roydukkey** [comment]
How about a pull request? ;)

**Comment by usmonster** [comment]
Hi @TheDigitalOrchard! v1.8.1 is functionally equivalent to v1.8.0 (see [release notes](/briancherne/jquery-hoverIntent/releases)), so it was decided to hold off on updating the gh-pages branch until the next version is ready, so closing the issue. Thanks for using the plugin!

**Comment by roydukkey** [comment]
@usmonster I think he means the download links on the website, not the version that the site is using.

Those probably should be updated, just in case people land there first from a search page.

http://cherne.net/brian/resources/jquery.hoverIntent.html

**Comment by usmonster** [comment]
Ah, I understand. This is also pretty minor, but the issue will also go away once I create the gh-pages branch and change the official site to briancherne.github.io/jquery-hoverIntent (not yet live). Search engines will reindex a bunch of stuff, and that will be that. :)

**Comment by usmonster** [comment]
....I guess in the meantime, I should create an issue for that, huh? ;)

**Comment by usmonster** [comment]
The branch has been created, and the site is live: https://briancherne.github.io/jquery-hoverIntent/ .

@briancherne, it's now just up to you to update the url in the repo description and close this issue. :)

I might suggest waiting for [release v1.9.0](https://github.com/briancherne/jquery-hoverIntent/milestones), which is coming soon!

**Comment by briancherne** [comment]
The cherne.net page now has a permanent redirect (301) to the GitHub repo.
