### ISSUE TITLE
make new version

### ISSUE THREAD

**Issue by lpalgarvio** [briancherne/jquery-hoverIntent#54]
Hello

Could you release a new version?

1.8.1 is dated from 2014 but is still being used in master in 2016...
it's greatly changed if you compare with a diff

**Comment by usmonster** [comment]
Hi! Thanks for using the plugin. A new release is pending--please feel free to follow the remaining milestone issues, here:
https://github.com/briancherne/jquery-hoverIntent/milestones/v1.9.0

In the meantime, I'll close this one. :)
