### ISSUE TITLE
Timeout only applys to mouseout method and doesn't affect mouseenter

### ISSUE THREAD

**Issue by amclin** [briancherne/jquery-hoverIntent#61]
The timeout value only applies to the method called on mouseout, and not the method called on mouseenter. So if you have several elements with mouseenter/out behaviors (example a menu where hovering one menu item should clear the hover on sibling menu items) then the mouseout delay is negated by the sibling elements having 0 delay for mouseenter

Pull Request #60 adds the ability to specify timeout values for mouseenter as well

**Comment by briancherne** [comment]
@amclin I appreciate the proactive pull request, but unfortunately I'm opposed to this feature request... if I understand it correctly.

The handlerIn function is already delayed by at least one polling interval. I don't see how adding an additional fixed delay for the handlerIn could be beneficial to the end user. I'm trying to stand by the principle that UI's need to be as-snappy-as-possible and not throw delays upon delays to fix some other delay. It sounds like you're trying to solve an implementation-specific usability issue.

Is there some generic use case that requires a fixed delay on handlerIn that I'm not seeing?

**Comment by usmonster** [comment]
I agree entirely with @briancherne.

@amclin I'm not sure, but the use case you describe sounds like it could be exactly the one mentioned on #6. (Please correct me if I'm wrong.) If that's the case, I would suggest reading the thread and proposed solutions on that issue (and maybe also peek at #9), which don't require a modification to the plugin itself.

Unless this is a significantly different use case you're describing, I'd rather close this issue, along with #60, and move the discussion to #6. What do you think?

**Comment by amclin** [comment]
My use case is very similar to #6 but it's not exclusively limited to sibling elements. I think allowing the plugin behavior to be symmetrical is a rather good way of solving the challenges of sibling or related elements. My scenarios is not solved by a shared intent on the container. Rather I need to make sure that the opening of a sibling doesn't prematurely close the original element.

**Comment by usmonster** [comment]
Hello again, and sorry for the extreme delay! I just reread the thread on #6, and based on what you said, it indeed does seem like the generic `sharesIntent` use case that Brian mentions. As I think more discussion is needed around the need for this kind of feature and the implementation approach, I'll close this (and #60 along with it) for now.

Please feel free to revive the discussion on #6, and thanks again for the interest and for your PR!
