### ISSUE TITLE
Is it work with dynamically added element?

### ISSUE THREAD

**Issue by kamiyeye** [briancherne/jquery-hoverIntent#62]
I tried the following code but no luck

`$(document).on('mouseenter.hoverIntent', element, function() {});`

**Comment by twidi** [comment]
As showed on https://briancherne.github.io/jquery-hoverIntent/, you should do something like

```js
$(document).hoverIntent(
    function() { console.log('in') },
    function() { console.log('out') },
    'selector'
)
```

It's what I do and it works on elements present at first and dynamically added ones

**Comment by usmonster** [comment]
Thanks @twidi for responding! :)

@kamiyeye, I'll close this issue for now, but please comment again if you think you've found a bug or limitation in the plug-in, or if you have any other directly-related follow-up question.

**Comment by twidi** [comment]
@usmonster: you're welcome, I just started using this plugin and as always, I do a quick check on issues and pull requests to know the actual defects, and seen this, as I just did it in my code, so... :)
