### ISSUE TITLE
cdnjs issue was opened

### ISSUE THREAD

**Issue by sashberd** [briancherne/jquery-hoverIntent#63]
Hi
There is a problem with you labrari on cdnjs
please check this conversation and provide solution
thank
https://github.com/cdnjs/cdnjs/issues/11656

**Comment by usmonster** [comment]
Hi! Thanks for bringing it to my attention. This is because we haven't yet officially released [v1.9.0](https://github.com/briancherne/jquery-hoverIntent/milestone/1), which is a real shame, so I'll try to do that today. :) In the meantime, I'll comment on the cdnjs issue and close this one.
