### ISSUE TITLE
Improperly triggers mouseout when hovering a child inputs auto complete suggestion.

### ISSUE THREAD

**Issue by mdunnerstick** [briancherne/jquery-hoverIntent#75]
This issue was closed, but it shouldn't be:
https://github.com/briancherne/jquery-hoverIntent/issues/46

The bug still exists.  A jfiddle was already set up to demonstrate this
http://jsfiddle.net/9x1cnteh/2/

* click the alpha button
* click in the input field
 *autocomplete dialog appears.  go to select something
* the mouseleave (or mouseout) is triggered, the box closes, and you can't select the autocomplete.

The correct behavior is that the google chrome auto complete doesn't triggered the mouse leave.

Google Chrome: Version 76.0.3809.100 (Official Build) (64-bit)
Mac Mojave: 10.14.6

**Comment by usmonster** [comment]
Hi, thanks for opening the issue, though it appears your fiddle doesn't use hoverIntent (it points to an old URL for the plugin, which is no longer valid), so the behavior you're seeing is just jQuery's `.hover()` in the end.

Can you please update the fiddle or create a new one? Thanks!

**Comment by mdunnerstick** [comment]
It's a problem with Chrome actually.  I'd just close it out.  I logged it with them.  Sorry for alerting you.

**Comment by anteksiler** [comment]
I have the same issue on Firefox, with the select button.  If you go to https://peakshops.fuelthemes.net/peakshops-furniture/ and then hover over search: 

- Text Input does not turn off the dropdown.
- Select Button does turn off the dropdown.
