### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by emarketmedia** [briancherne/jquery-hoverIntent#78]
Hello,
I loaded a code:

       $(document).ready(function(){
            $("#sidebar").hoverIntent(alert("mouseover"),alert("mouseout"));
        });

..to make a test.

Result is only two errors on log.

![Schermata 2019-10-16 alle 12 08 17](https://user-images.githubusercontent.com/11158087/66909860-c90fae80-f00d-11e9-8103-009ba58babbe.png)

Please check, thanks.

**Comment by roydukkey** [comment]
Do this produce an errors?
```js
$(document).ready(function(){
     $("#sidebar").hoverIntent(function(){alert("mouseover")},function(){alert("mouseout")});
});
```

**Comment by emarketmedia** [comment]
Working fine! Thanks!

**Comment by usmonster** [comment]
Thanks @emarketmedia for reporting, and thanks @roydukkey for responding.

Indeed, your issue was that the plugin wasn't being invoked properly as you were invoking `alert()`, which has no return value (`undefined`), instead of passing a function.

I'll close this ticket. :)
