### ISSUE TITLE
Failed to open stream

### ISSUE THREAD

**Issue by osamasado** [briancherne/jquery-hoverIntent#85]
Drupal: Version 10

Warning: file_get_contents(libraries/jquery-hoverIntent/jquery.hoverIntent.js): Failed to open stream: No such file or directory in _locale_parse_js_file() (line 1097 of core/modules/locale/locale.module).

**Comment by usmonster** [comment]
Hello! This seems to be a Drupal issue, not an issue with the plugin, so I'm closing it. Feel free to open an issue with Drupal—thanks!
